version: '3'
services:
    node-dev:
        build:
            context: ./docker
            dockerfile: dockerfile-dev
        volumes:
            - ./app/:/usr/src/app
        ports:
            - '3001:3000'
