version: '3'
services:
    node-prod:
        build:
            context: ./docker
            dockerfile: dockerfile-prod
        volumes: 
            - ./app/:/usr/src/app
        ports: 
            - '3000:3000'
