FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
# COPY package.json .

RUN apt install bash
RUN npm install


# Bundle app source
# COPY run.sh run.sh

# Exports
EXPOSE 3000
CMD [ "npm", "run", "start" ]